disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "ramongomez.xyz"

[params]
  displayName = "EN"
  isoCode = "en"
  dateFormat = "2 January 2006"
  description = "Ram贸n G贸mez's Portfolio"

[params.author]
  name = "Ram贸n G贸mez"
  email = "ramon@ramongomez.xyz"
  headline = "Software Engineer, Tech enthusiast and passionate about Specialty Coffee making"
  bio = "Software Engineer, Tech enthusiast and passionate about Specialty Coffee making"
  image = "MonfraguePI_1.png"
  imageQuality = 60
  links = [{github = "https://github.com/rgomezr"}, {substack = "https://substack.com/@rgomezr"} ]